[workspace]

members = [
    "artemis",
    "artemis_codegen",
    "artemis-build",
    "artemis-test",
    "artemis-load-gen",
    "artemis-normalized-cache",
    "artemis-codegen-proc-macro"
]

[profile.release]
lto = true
debug = true