[package]
name = "artemis"
version = "0.1.0"
authors = ["Genna Wingert <wingertge@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
futures = "0.3"
surf = { git = "https://github.com/http-rs/surf.git" }
serde_json = "1"
async-trait = "0.1"

[dev-dependencies]
artemis-tests = { path = "../artemis-tests" }
tokio-test = "0.2"