[package]
name = "artemis"
version = "0.1.0"
authors = ["Genna Wingert <wingertge@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
futures = "0.3"
surf = "1"
serde_json = "1"
async-trait = "0.1"
http = "0.2"