[package]
name = "artemis"
version = "0.1.0"
authors = ["Genna Wingert <wingertge@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
futures = "0.3"
surf = { git = "https://github.com/http-rs/surf.git" }
serde_json = "1"
async-trait = "0.1"
bincode = "1"

[dev-dependencies]
artemis-test = { path = "../artemis-test" }
tokio = { version = "0.2", features = ["full"] }
lazy_static = "1"