[package]
name = "artemis"
version = "0.1.0"
authors = ["Genna Wingert <wingertge@gmail.com>"]
edition = "2018"

[[bench]]
name = "integration_bench"

[features]
default = ["observable", "default-exchanges"]
observable = ["tokio", "stable-vec"]
default-exchanges = ["surf"]

[dependencies]
serde = { version = "1", features = ["derive"] }
futures = "0.3"
serde_json = "1"
async-trait = "0.1"
bincode = "1"
parking_lot = "0.10"
type-map = "0.3"

surf = { git = "https://github.com/http-rs/surf.git", optional = true }

tokio = { version = "0.2", optional = true }
stable-vec = { version = "0.4", optional = true }

[dev-dependencies]
artemis-test = { path = "../artemis-test" }
tokio = { version = "0.2", features = ["full"] }
lazy_static = "1"
criterion = "0.3"
criterion-macro = "0.3"
rand = "0.7"
tokio-test = "0.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2", features = ["nightly"] }
js-sys = "0.3"
wasm-bindgen-futures = "0.4"