name: 'Linux (GNU)'

on:
  push:
    branches-ignore: gh-pages

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run Test Backend
      run: "docker run -d --name graphql-demo -p 8080:8080 npalm/graphql-java-demo"
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
