name: 'Linux (Beta)'

on:
  push:
    branches-ignore: gh-pages

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install latest beta
      uses: actions-rs/toolchain@v1
      with:
        toolchain: beta
        override: true
    - name: Run Test Backend
      run: "docker run -d --name graphql-demo -p 8080:8080 npalm/graphql-java-demo"
    - name: Build
      run: cargo +beta build --verbose
    - name: Run tests
      run: cargo +beta test --verbose
