name: 'Linux (Nightly)'

on:
  push:
    branches-ignore: gh-pages

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Run Test Backend
      run: "docker run -d --name graphql-demo -p 8080:8080 npalm/graphql-java-demo"
    - name: Build
      run: cargo +nightly build --verbose
    - name: Run tests
      run: cargo +nightly test --verbose
    - name: Generate docs
      run: cargo +nightly doc
    - name: Patch docs index
      run: echo "<meta http-equiv=refresh content=0;url=artemis/index.html>" > target/doc/index.html
    - name: Push docs to GitHub pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: target/doc # The folder the action should deploy.